#!/bin/bash

# Read up to the first three lines from standard input
read -r USER || USER=""
read -r PASS || PASS=""
read -r TOTP || TOTP=""

type_sleep=45
next_sleep=250

# Use wtype to output the USER and PASS
$BWZY_TYPE_CMD \
  -d $type_sleep "$USER" \
  -s $next_sleep \
  -k tab \
  -s $next_sleep \
  -d $type_sleep "$PASS" \
  -s $next_sleep \
  -k return

[[ -n "$BWZY_NOTIFY_CMD" ]] && $BWZY_NOTIFY_CMD "user & pass autofilled"

# Copy the TOTP to clipboard
if [[ -n "$TOTP" ]]; then
    echo -n "$TOTP" | cli-copy
    [[ -n "$BWZY_NOTIFY_CMD" ]] && $BWZY_NOTIFY_CMD "TOTP copied to clipboard"
fi

